### ISSUE TITLE
建议把lua的动态库独立出来

### ISSUE THREAD

**Issue by Layty** [chenxuuu/llcom#120]
## 描述一下这个bug / Describe the bug
我用C++新增了一个模块, 动态链接是lua-5.4.4 , 然后在脚本中require 直接崩溃了.
我应该怎么做? 你这里的lua是哪个版本的

## 复现步骤 / To Reproduce
按照下面的步骤，可以复现bug / Steps to reproduce the behavior:
直接require 崩溃

## 预期的行为 / Expected behavior
清楚简洁地描述你希望发生的事情。 / A clear and concise description of what you expected to happen.
是否可以把动态库独立出来

## 截图 / Screenshots
如果需要，请放上你的截图。 / If applicable, add screenshots to help explain your problem.

## 日志 / Logs
`更多设置`--`打开串口收发日志目录`，可以看到日志 / Upload your log files.

## 系统信息 / Desktop (please complete the following information):
 - 如果可以，可以附加配置文件内容（`更多设置`--`打开串口收发日志目录`--切换到上一级目录--`settings.json`文件）

**Comment by chenxuuu** [comment]
xlua x64
lua5.3



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月10日(周五) 下午5:21
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [chenxuuu/llcom] 建议把lua的动态库独立出来 (Issue #120)




 
描述一下这个bug / Describe the bug
 
我用C++新增了一个模块, 动态链接是lua-5.4.4 , 然后在脚本中require 直接崩溃了.
 我应该怎么做? 你这里的lua是哪个版本的
 
复现步骤 / To Reproduce
 
按照下面的步骤，可以复现bug / Steps to reproduce the behavior:
 直接require 崩溃
 
预期的行为 / Expected behavior
 
清楚简洁地描述你希望发生的事情。 / A clear and concise description of what you expected to happen.
 是否可以把动态库独立出来
 
截图 / Screenshots
 
如果需要，请放上你的截图。 / If applicable, add screenshots to help explain your problem.
 
日志 / Logs
 
更多设置--打开串口收发日志目录，可以看到日志 / Upload your log files.
 
系统信息 / Desktop (please complete the following information):
  
OS: [e.g. iOS]
 
Version [e.g. 22]
 
如果可以，可以附加配置文件内容（更多设置--打开串口收发日志目录--切换到上一级目录--settings.json文件）
  
其他备注信息 / Additional context
 
Add any other context about the problem here.

**Comment by Layty** [comment]
还是会崩溃,大佬又没试过导入自己用c或者cpp写的dll, 我用5.3.6编译的lua 以及动态库可以导入,在llcom上无法导入

**Comment by chenxuuu** [comment]
1. 你可以直接把你的dll贴在这里，看看到底是什么编译参数
2. 之前测试过该类功能，可用：https://github.com/chenxuuu/llcom/issues/22#issuecomment-738548865 （当时使用的是x86目标架构，需要配合当时的llcom版本运行测试）

**Comment by Layty** [comment]
我是绑定到C++上
代码放在这里  https://github.com/Layty/LuaLib/tree/main/lua

![image](https://user-images.githubusercontent.com/14368090/224593015-dc4c33f9-d1e3-4969-9fcb-281d64f3f61c.png)

**Comment by chenxuuu** [comment]
直接把你测试用的dll贴在这里

**Comment by Layty** [comment]
https://cowtransfer.com/s/d836c236668c4b 点击链接查看 [ mylib.rar ] ，或访问奶牛快传 cowtransfer.com 输入传输口令 ahkd8v 查看；      奶牛快传的连接

**Comment by chenxuuu** [comment]
请直接提供**能让我直接复现你说的问题**的测试脚本与DLL文件

**Comment by chenxuuu** [comment]
issue模板里的**复现步骤**你觉得能让我复现出来吗

**Comment by Layty** [comment]
重新传了,压缩包如下,里面log为空
![image](https://user-images.githubusercontent.com/14368090/224615550-91f145be-4d96-47d7-9b35-348445a3d45c.png)

压缩包在这里 
 https://cowtransfer.com/s/e0b785f4136540 点击链接查看 [ mytest.rar ] ，或访问奶牛快传 cowtransfer.com 输入传输口令 f2nnl4 查看；


脚本如下
require "libEasy"
vv=LuaGetVec("11223344")
print(LuaVecToString(vv))


lua直接运行hello.lua 可以 成功
![image](https://user-images.githubusercontent.com/14368090/224615163-a9d53125-5d2d-4c4f-82eb-8760a1ce161a.png)

llcom 有时候运行直接崩溃,退出程序

![image](https://user-images.githubusercontent.com/14368090/224615398-0bb885d0-b18a-48f9-9489-ad29791f1efe.png)

有时候提示 
![image](https://user-images.githubusercontent.com/14368090/224615433-c9934b7c-1522-4344-9196-f6af4d30b5b7.png)

**Comment by chenxuuu** [comment]
根据截图，报错信息是死在了`lua\LuaBridge\Source\LuaBridge\detail\Namespace.h`文件的断言里，并不是死在llcom中：
![图片](https://user-images.githubusercontent.com/10357394/224616595-c98412ab-bce0-41f6-a221-781e9d88129e.png)

软件调用的dll崩溃，也会导致软件闪退，这很正常

建议先排查一下为何在此处崩溃
