### ISSUE TITLE
能否添加使窗口固定在最前面的功能

### ISSUE THREAD

**Issue by apan-pro** [chenxuuu/llcom#129]
## 您的功能请求是否与解决某些问题有关？请描述一下。/ Is your feature request related to a problem? Please describe.
能否添加使窗口固定在最前面的功能
## 描述您想要的解决方案 / Describe the solution you'd like
在标题栏最小化按钮旁边或其他地方添加一个按钮使窗口锁定在最前面，再点一次按钮取消锁定。
## 描述您考虑过的替代方案 / Describe alternatives you've considered
无
## 其他备注信息
无

**Comment by chenxuuu** [comment]
设置里有窗口置顶开关



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月19日(周三) 上午10:54
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [chenxuuu/llcom] 能否添加使窗口固定在最前面的功能 (Issue #129)




 
您的功能请求是否与解决某些问题有关？请描述一下。/ Is your feature request related to a problem? Please describe.
 
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
 能否添加使窗口固定在最前面的功能
 
描述您想要的解决方案 / Describe the solution you'd like
 
A clear and concise description of what you want to happen.
 在标题栏最小化按钮旁边或其他地方添加一个按钮使窗口锁定在最前面，再点一次按钮取消锁定。
 
描述您考虑过的替代方案 / Describe alternatives you've considered
 
A clear and concise description of any alternative solutions or features you've considered.
 无
 
其他备注信息
 
Add any other context or screenshots about the feature request here.
 无

**Comment by apan-pro** [comment]
好的，感谢回复

**Comment by chenxuuu** [comment]
开着吧，置顶按钮确实应该放到窗口上



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月19日(周三) 中午11:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chenxuuu/llcom] 能否添加使窗口固定在最前面的功能 (Issue #129)




 
好的，感谢回复
