### ISSUE TITLE
再请教一个关于uartReceive回调触发机制的问题

### ISSUE THREAD

**Issue by qnxsgwy** [chenxuuu/llcom#73]
目前uartReceive回调的触发机制是什么怎样的?
如果uartReceive回调内处理数据比较慢，比如五毫秒才能处理完，但是数据又来的比较快，一毫秒后就来了。这时候是会触发一个新回调，两个回调同时并行执行，还是数据先放在缓冲区，等上一个回调完成后再触发新的回调?

**Comment by chenxuuu** [comment]
lua不支持多线程



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月7日(周三) 晚上11:42
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [chenxuuu/llcom] 再请教一个关于uartReceive回调触发机制的问题 (Issue #73)




 
目前uartReceive回调的触发机制是什么怎样的?
 如果uartReceive回调内处理数据比较慢，比如五毫秒才能处理完，但是数据又来的比较快，一毫秒后就来了。这时候是会触发一个新回调，两个回调同时并行执行，还是数据先放在缓冲区，等上一个回调完成后再触发新的回调?

**Comment by qnxsgwy** [comment]
> lua不支持多线程
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年9月7日(周三) 晚上11:42 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [chenxuuu/llcom] 再请教一个关于uartReceive回调触发机制的问题 (Issue #73) 目前uartReceive回调的触发机制是什么怎样的? 如果uartReceive回调内处理数据比较慢，比如五毫秒才能处理完，但是数据又来的比较快，一毫秒后就来了。这时候是会触发一个新回调，两个回调同时并行执行，还是数据先放在缓冲区，等上一个回调完成后再触发新的回调? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

也就是说类似nodejs，有个任务队列，回调函数多次触发就会放入队列，一个个按顺序执行?

**Comment by chenxuuu** [comment]
差不多



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月8日(周四) 凌晨1:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chenxuuu/llcom] 再请教一个关于uartReceive回调触发机制的问题 (Issue #73)




  
lua不支持多线程
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2022年9月7日(周三) 晚上11:42 收件人: @.&gt;; 抄送: @.&gt;; 主题: [chenxuuu/llcom] 再请教一个关于uartReceive回调触发机制的问题 (Issue #73) 目前uartReceive回调的触发机制是什么怎样的? 如果uartReceive回调内处理数据比较慢，比如五毫秒才能处理完，但是数据又来的比较快，一毫秒后就来了。这时候是会触发一个新回调，两个回调同时并行执行，还是数据先放在缓冲区，等上一个回调完成后再触发新的回调? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt;
  
也就是说类似nodejs，有个任务队列，回调函数多次触发就会放入队列，一个个按顺序执行?
